public class two {

        /*

        Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
        find the sum of the even-valued terms.

        */

        public static void main(String[] args){
                int previousFibNum = 1;
                int currentFibNum = 2;
                int temp;
                int fibSum = 3;
                while (currentFibNum < 4000000){
                        if (currentFibNum % 2 == 0){
                                fibSum += currentFibNum;
                        }
                        temp = currentFibNum;
                        currentFibNum = currentFibNum + previousFibNum;
                        previousFibNum = temp;
                }
                System.out.printf("The sum is %d\n", fibSum);
        }
        
}
